# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20171112_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='price',
            field=models.DecimalField(decimal_places=2, default='300', max_digits=6),
        ),
        migrations.AddField(
            model_name='training',
            name='min_attendees',
            field=models.IntegerField(default='0'),
        ),
    ]
