# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_auto_20171112_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('stripe_id', models.CharField(max_length=40)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='services.Training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
