# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_trainingpurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingpurchase',
            old_name='date',
            new_name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='trainingpurchase',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='trainingpurchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingpurchase',
            name='training_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
