# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0005_auto_20180210_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('consultancy_date', models.DateField(default=django.utils.timezone.now)),
                ('consultancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_purhcases', to='services.Consultancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='trainingpurchase',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_purchases', to='services.Training'),
        ),
        migrations.AlterField(
            model_name='trainingpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
