# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_auto_20171208_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='email',
            field=models.CharField(default='test@test.com', max_length=100),
            preserve_default=False,
        ),
    ]
