# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_testimonial_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='email',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='first_name',
            field=models.CharField(default='change_me', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='initial',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL),
        ),
    ]
